FROM node:20-alpine

RUN corepack enable
WORKDIR /app

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
COPY frontend/package.json frontend/package.json

RUN pnpm install --frozen-lockfile

COPY frontend ./frontend
WORKDIR /app/frontend

EXPOSE 3001
CMD ["pnpm", "run", "dev"]
